# @package cebra

# A descriptive name for this configuration
name: cebra7dim3.1

model_architecture: 'offset1-model'
# CEBRA-specific parameters
output_dim: 3
max_iterations: 10000
conditional: 'None'
# Nested parameters for the model
params:
  batch_size: 512
  learning_rate: 3e-4 # Higher learning rate
  temperature: 1.0
  distance: 'cosine' # Different distance metric
  verbose: True
