# @package cebra
# A descriptive name for this configuration
name: cebra7dim2

model_architecture: 'offset1-model' #<-- Add the parameter here

# CEBRA-specific parameters
output_dim: 2
max_iterations: 10000
conditional: 'discrete'
# Nested parameters for the model
params:
  batch_size: 512
  learning_rate: 3e-4 # Higher learning rate
  temperature: 1.0
  distance: 'cosine' # Different distance metric
  verbose: True