# @package cebra
# A descriptive name for this configuration
name: model8cosdis

model_architecture: offset0-model

# CEBRA-specific parameters
output_dim: 3
max_iterations: 15000
conditional: 'discrete'
# Nested parameters for the model
params:
  batch_size: 512
  learning_rate: 3e-4 # Higher learning rate
  temperature: 1.0
  distance: 'cosine' # Different distance metric
  verbose: True
